Open the files in text mode, not binary mode
Fix for:
Traceback (most recent call last):
File "../../../../frida-core/src/generate-api.py", line 180, in <module>
output_deps_file.write("glib-2.0")
TypeError: 'str' does not support the buffer interface mode